### ISSUE TITLE
endを送信して処理が終了した時にはそれぞれのコンソールウィンドウを消す

### ISSUE THREAD

**Issue by ClairdelunaEve** [aais-lab/MultiAgentSystem#7]
## 概要
endが送信されて処理が終了した時にはコンソールを閉じて欲しい

## 要望の詳細
- 性質上、かなりの数のウィンドウが立ち上がったままになる
- ひとつひとつ手作業で消すのが面倒
- 自動的に閉じて欲しい

## その他
-

**Comment by ClairdelunaEve** [comment]
終了できなくはなさそう…？

- terminalを生成している関数はutilsの中のcreate_terminal
- subprocess.runはpidが取れないので、popen -> communicateで取得できないか検討してみる
- どっかで戻り値として保持するとか何かしらの対策してみるがどうかな…？

**Comment by ClairdelunaEve** [comment]
同時間にAGENT系のプロセスと-zshのプロセスが立ち上がるのでもしかしたら時間ベースでPIDを取得して殺す方がいいかも？

**Comment by sinil-sin-nil** [comment]
def close_all_terminals(self):
        applescript_code = """
        tell application "Terminal"
            set allWindows to every window
            repeat with w in allWindows
                tell w
                    do script "end" in selected tab
                    delay 0.5 -- wait for a moment to allow the command to execute
                end tell
            end repeat
            close every window
        end tell
        """

**Comment by sinil-sin-nil** [comment]
`    def close_all_terminals(self):
        applescript_code = """
        tell application "Terminal"
            set allWindows to every window
            repeat with w in allWindows
                tell w
                    do script "end" in selected tab
                    delay 0.5 -- wait for a moment to allow the command to execute
                end tell
            end repeat
            close every window
        end tell
        """
`

**Comment by ClairdelunaEve** [comment]
手元環境以外で動作未確認

**Comment by ClairdelunaEve** [comment]
## コード
```
tell application "Terminal"
    set all_windows to every window
    repeat with cur_window in all_windows
        if name of cur_window contains "USER" then
            tell cur_window
                do script "end" in selected tab
                delay 2
            end tell
        end if
        if name of cur_window does not contain "MAS.command" then
            set tempID to id of cur_window
            tell the window id tempID to close
        end if
    end repeat
end tell
```
## 仕様

- 現在起動している全てのTerminal windowに対して繰り返す
- 現在のwindow名にUSERが含まれているときには"end"を送信して2秒待機
- 現在のwindow名にMAS.commandが含まれていない場合killする

## 利用箇所

- MAS.commandの中の、コンテナ停止前
- MAS.pyの中で実行ボタン押下時に最初に走る

**Comment by ClairdelunaEve** [comment]
非同期処理なので実行ボタンでterminalを閉じる際は待機時間を1秒とる
2秒だと目に見えて遅延したので、1秒にした

**Comment by ClairdelunaEve** [comment]
@sinil-sin-nil 
有益な情報ありがとうございました

**Comment by sinil-sin-nil** [comment]
@ClairdelunaEve 
こちらこそお役に立てたならよかったです！！！
